# Results

Twenty-two bird species were recorded over the 363 sampling points, with a mean of species per point and species per 100-m elevational band along the gradient. Fourteen species were exotic and eight native [@tbl:species]. The number of records varied widely across species between 1 for two species (*,* ) and 268 for ** (mean: $\pm$ s.d.: , Fig. \[boxalti\]).

Amplitudes in elevational range were high. Elevational amplitude exceeded 2000 m for five species and 1000 m for 15 species (Table 1). The largest elevational amplitude measured in native species was for *Zosterops borbonicus* (92 % of the gradient) and for *Acridotheres tristis* in exotic species (83 %) . The lowest elevational amplitude measured in native species was registered for *Circus maillardi* (20 %) and for *Perdicula asiatica* in exotic species (8 %). The distribution of weighted mid-points, that is the weighted mean of elevations where a species occurs along the gradient, was highly concentrated between 1000 and 1500 m, with the exception of three exotic species ([@Fig:boxrange]). The weighted mid-point and minimum elevation were however higher in native species ($p=0.034$ and $p=0.024$). By contrast, elevational amplitude and maximum elevation did not differ significantly between the two groups of species ($p=0.534$ and $p=0.254$ respectively, [@Fig:boxrange]). No difference in the variability of species distribution was observed across the two groups: Bartlett test’s of variance homogeneity showed that the variability was similar in the two groups for the four tested variables.

The total species richness observed within 100-m elevation bands varied between 2 and 19 (10.4 $\pm$ 5.5, [@Fig:Sgam].a). Total richness showed a unimodal mid-elevational peak between 1000 and 1200 m. However, the pattern of species richness differed significantly between exotic and native species with increasing elevation ([@Fig:Sgam]). Species
richness varied between 0 and 7 for native birds (3.5 $\pm$ 2.2), and between 1 and 12 (6.9 $\pm$ 3.9) for exotic birds ([@Fig:Sgam].b). Species richness showed different elevational patterns across the two groups. Species richness of native birds showed a unimodal mid-elevational peak around 1200 m, whereas richness for exotic birds species showed a low-elevation plateau with a small mid-peak also around 1200 m. Exotic species were more numerous than native birds up to mid-elevation, whereas native species were more numerous at higher altitudes ([@Fig:Sgam].b). According to richness patterns, three zones could be defined: (1) from 0 to 900 m, there was a significant difference between exotic and native species, both in the number of species contacted and in their variation pattern, as native species increased with the elevational gradient from two to seven while the exotic ones remained at a high level (around 9 species ); (2) from 1000 to 2000 m, richness of both exotic and native species presented a peak (around 9 and 6 species, respectively); (3) from 2000 to 3000 m, richness was higher in native species while exotic species were barely present.

In order to explore species co-occurence according to their status, we compared species richness to random patterns obtained by simulation. Values occurring within the simulated 95% confidence band for the random pattern indicated elevation bands where species richness was not statistically different from random patterns of species assemblage [@Fig:Snul]. In both groups, null patterns showed higher variability at low and high elevation when sites were all considered as equally suitable (randomized total abundance), whereas null patterns were more constrained when the total abundance observed at each site was kept constant (site capacity hypothesis). All models showed mid-elevation peaks however less pronounced under the site capacity hypothesis.

Native species richness was significantly lower than random expectations at low elevation for both null models ([@Fig:Snul].a). This finding indicates depauperate communities where native species occur less frequently than expected by chance. From 900 m above, the observed pattern in native species richness overall supported more the site capacity hypothesis Regarding exotic birds, species richness was lower than expected by chance above 1500 m high ([@Fig:Snul].b). This result indicates that exotic species in high elevation bird communities are in low numbers compared to the site capacity. At low to mid altitude, the observed pattern in exotic species richness was closer to the confidence interval of the null model without constraint on site capacity (equally suitable hypothesis). The site capacity hypothesis generated higher than observed numbers of exotic species.

